app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: '%app_locales%'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fr
        permanent: false