services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    validator.date.reservation:
        class: AppBundle\Validator\Constraints\constraintsCheckDateReservationValidator
        arguments:
            - "@app.checkIfDateIsBefore"
            - "@app.checkIfDateInList"
        tags:
            - { name: validator.constraint_validator }

    validator.type.ticket:
        class: AppBundle\Validator\Constraints\constraintsCheckTypeTicketValidator
        arguments:
            - "@app.checkIf14Hour"
        tags:
            - { name: validator.constraint_validator }

    app.checkIfDateIsBefore:
        class: AppBundle\Services\CheckIfDateIsBefore

    app.checkIfDateInList:
        class: AppBundle\Services\CheckIfDateInList
        arguments:
            - "@app.generateListDateDisabled"

    app.checkIf14Hour:
        class: AppBundle\Services\CheckIf14Hour

    app.generatePrices:
        class: AppBundle\Services\GeneratePrices
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.getAge"

    app.getAge:
        class: AppBundle\Services\GetAge

    app.createTicket:
        class: AppBundle\Services\CreateTicket

    app.sendEmail:
        class: AppBundle\Services\SendEmail
        arguments:
            - "@templating"
            - "@mailer"

    app.saveClient:
        class: AppBundle\Services\GestionClient
        arguments:
            - "@doctrine.orm.entity_manager"

    app.getSessionClient:
        class: AppBundle\Services\GestionClient
        arguments:
            - "@doctrine.orm.entity_manager"

    app.setSessionClient:
        class: AppBundle\Services\GestionClient
        arguments:
            - "@doctrine.orm.entity_manager"

    app.generateListDateDisabled:
        class: AppBundle\Services\GenerateListDateDisabled
        arguments:
            - "@doctrine.orm.entity_manager"